languageCode = "en-us"
title = "Ikue Ueno"
baseurl = "https://www.ikueueno.com/"
theme = "prologue"
publishDir = "docs"

[params]
  name = "Ikue Ueno"
  description = "Professional dancer"
  copyright = "Untitled."

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/Ikuedancer"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/ikuedancer/"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/user/IkueDancer"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:ikuedancer@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Dancer"
  alt = ""
  source = "img/portolio_1.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio1]]
  title = "Performer"
  alt = ""
  source = "img/portolio_2.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio1]]
  title = "Choreographer"
  alt = ""
  source = "img/portolio_3.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio1]]
  title = "Freestyler"
  alt = ""
  source = "img/portolio_4.jpg"
  url = "https://www.instagram.com/ikuedancer/"


# Portfolio column two

[[params.portfolio2]]
  title = "Dancer teacher"
  alt = ""
  source = "img/portolio_5.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio2]]
  title = "Live on stage"
  alt = ""
  source = "img/portolio_6.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio2]]
  title = "Spiritual"
  alt = ""
  source = "img/portolio_7.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio2]]
  title = "Street dancer"
  alt = ""
  source = "img/portolio_8.jpg"
  url = "https://www.instagram.com/ikuedancer/"


# Portfolio column three

[[params.portfolio3]]
  title = "Voguing dancer"
  alt = ""
  source = "img/portolio_9.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio3]]
  title = "Club kid"
  alt = ""
  source = "img/portolio_10.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio3]]
  title = "Waacking dancer"
  alt = ""
  source = "img/portolio_11.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio3]]
  title = "Contemporary dancer"
  alt = ""
  source = "img/portolio_12.jpg"
  url = "https://www.instagram.com/ikuedancer/"
