languageCode = "en-us"
title = "Ikue Ueno"
baseurl = "https://www.ikueueno.com/"
theme = "prologue"
publishDir = "docs"

[params]
  name = "Ikue Ueno"
  description = "Professional dancer"
  copyright = "Untitled."

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/Ikuedancer"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/ikuedancer/"

[[params.social]]
  medium = "youtube"
  icon = "youtube"
  link = "https://www.youtube.com/user/IkueDancer"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:ikuedancer@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Dance teacher"
  alt = ""
  source = "img/portolio_1.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio2]]
  title = "Dancer"
  alt = ""
  source = "img/portolio_2.jpg"
  url = "https://www.instagram.com/ikuedancer/"

[[params.portfolio3]]
  title = "Choreographer"
  alt = ""
  source = "img/portolio_3.jpg"
  url = "https://www.instagram.com/ikuedancer/"

# Portfolio column two